name: Build Animate

on:
  # Push to main or PR
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build Animate"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: jwallwork/firedrake-parmmg:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Animate
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip uninstall -y animate
          python -m pip install -e .
      - name: Test Animate
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m coverage erase
          python -m coverage run --source=animate -m pytest -v --durations=20 test
          python -m coverage report
      - name: Lint
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint
