name: 'Citation Check'

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cff'

  pull_request:
    paths:
      - '**/*.cff'

  workflow_dispatch:

jobs:
  citation_check:
    uses: mesh-adaptation/mesh-adaptation-docs/.github/workflows/citation_check.yml@45_reusing_workflows